# Generated by Django 5.0.2 on 2024-03-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=100)),
                ('rollNo', models.IntegerField(unique=True)),
                ('ownerEmail', models.EmailField(max_length=254)),
                ('accessCode', models.CharField(max_length=100)),
            ],
        ),
    ]
